# Generated by Django 2.0.4 on 2018-04-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.CharField(default='coffe1.png', max_length=1000),
            preserve_default=False,
        ),
    ]
